# =====================================================
# Nav2 + SLAM Toolbox configuration
# Robot differenziale indoor - corridoi min 50 cm
# =====================================================
bt_navigator:
  ros__parameters:
    use_sim_time: false
    plugin: "nav2_bt_navigator::BehaviorTreeNavigator"
    bt_xml_filename: "/home/robot/nav2_behavior_trees/navigate_w_replanning_and_recovery.xml"
    autostart: true
    allow_initial_pose_reuse: true
    replanning_interval: 0.2
    transform_tolerance: 0.1    # tolleranza di 0.2 secondi    

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    transform_tolerance: 0.1
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.5
      smooth_path: false      # meno smoothing -> path più segmentato
      cost_travel_multiplier: 2.5
      cost_penalty_multiplier: 3.0
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    transform_tolerance: 0.1
    min_x_velocity_threshold: 0.1
    min_theta_velocity_threshold: 0.2
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

      # Velocità massime ridotte ~10%
      max_vel_x: 0.195    # prima 0.216
      min_vel_x: 0.0
      max_vel_theta: 1.9  # prima 2.136
      min_speed_xy: 0.0
      max_speed_xy: 0.195
      min_speed_theta: 0.0

      # Accelerazioni ridotte in proporzione
      acc_lim_x: 0.18     # prima 0.20
      acc_lim_theta: 1.0  # prima 1.2
      decel_lim_x: -0.25
      decel_lim_theta: -1.5

      # Parametri di simulazione DWB
      sim_time: 1.5
      vx_samples: 10
      vy_samples: 0
      vtheta_samples: 20
      # Lista dei critics
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

      # Config critics
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      Oscillation.scale: 0.0

      # Bias di traiettoria
      path_distance_bias: 32.0   # segui bene il path
      goal_distance_bias: 24.0   # avvicinati al goal
      occdist_scale: 0.05        # evita ostacoli senza strafare

      # Rotazioni sul posto
      rotate_to_heading_angular_vel: 1.0
      stop_time_buffer: 0.2
      oscillation_reset_dist: 0.05

      # Tolleranze goal
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.15
      trans_stopped_velocity: 0.01
      theta_stopped_velocity: 0.01

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 15.0
    max_velocity: [0.195, 0.0, 1.9]   # ridotte del 10%
    min_velocity: [-0.195, 0.0, -1.9]
    max_accel: [0.18, 0.0, 1.0]
    max_decel: [-0.25, 0.0, -1.5]

# ----------------- COSTMAPS -----------------

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 6.0
    publish_frequency: 3.0
    transform_tolerance: 0.3
    resolution: 0.07
    robot_radius: 0.17
    plugins: ["obstacle_layer","inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: laser_scan_sensor
      laser_scan_sensor:
        sensor_frame: laser_frame
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.1
        raytrace_max_range: 3.5
        raytrace_min_range: 0.1

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.30
      cost_scaling_factor: 1.1

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 12.0
    publish_frequency: 6.0
    transform_tolerance: 0.3
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.07
    robot_radius: 0.17
    plugins: ["obstacle_layer","inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: laser_scan_sensor
      laser_scan_sensor:
        sensor_frame: laser_frame
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        obstacle_max_range: 2.5
        obstacle_min_range: 0.1
        raytrace_max_range: 3.0
        raytrace_min_range: 0.1

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.20
      cost_scaling_factor: 2.0

# ----------------- RECOVERIES -----------------
back_up:
  ros__parameters:
    plugin: "nav2_recoveries::BackUp"
    backup_distance: 0.3
    velocity: 0.1

# ----------------- LIFECYCLE MANAGER -----------------
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ["slam_toolbox","planner_server","controller_server","recoveries_server","bt_navigator","velocity_smoother"]

