# =====================================================
# Nav2 + SLAM Toolbox configuration
# Robot differenziale indoor - corridoi min 40 cm
# =====================================================

# -------------------------------------------------
# BT Navigator
# -------------------------------------------------
bt_navigator:
  ros__parameters:
    use_sim_time: false
    plugin: "nav2_bt_navigator::BehaviorTreeNavigator"
    bt_xml_filename: "/home/robot/nav2_behavior_trees/navigate_w_replanning_and_recovery.xml"
    autostart: true
    allow_initial_pose_reuse: true
    replanning_interval: 0.1
    transform_tolerance: 0.1

# -------------------------------------------------
# Planner Server (NavFn sotto GridBased)
# -------------------------------------------------
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins:
      - "GridBased"
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true
      default_tolerance: 0.5
      cost_travel_multiplier: 1.2
      cost_penalty_multiplier: 1.0
      visualize: true

# -------------------------------------------------
# Controller Server (MPPI Controller)
# -------------------------------------------------
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    transform_tolerance: 0.1
    min_x_velocity_threshold: 0.08
    min_theta_velocity_threshold: 0.005
    controller_plugins:
      - "FollowPath"
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: "DiffDrive"
      iteration_count: 1
      model_dt: 0.05
      time_steps: 56
      batch_size: 2000
      vx_max: 0.216
      vx_min: -0.216
      vy_max: 0.0
      wz_max: 2.136
      ax_max: 0.18
      ax_min: -0.28
      ay_max: 0.0
      az_max: 1.2
      critics:
        - "ConstraintCritic"
        - "CostCritic"
        - "GoalCritic"
        - "GoalAngleCritic"
        - "PathAlignCritic"
        - "PathFollowCritic"
        - "PathAngleCritic"
        - "PreferForwardCritic"
      ConstraintCritic:
        cost_power: 1
        cost_weight: 4.0
      CostCritic:
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      GoalCritic:
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PathAlignCritic:
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0
      PreferForwardCritic:
        cost_power: 1
        cost_weight: 5.0

# -------------------------------------------------
# Velocity Smoother
# -------------------------------------------------
velocity_smoother:
  ros__parameters:
    smoothing_frequency: 15.0
    max_velocity:
      - 0.216
      - 0.0
      - 2.136
    min_velocity:
      - -0.216
      - 0.0
      - -2.136
    max_accel:
      - 0.18
      - 0.0
      - 1.2
    max_decel:
      - -0.28
      - 0.0
      - -1.8

# -------------------------------------------------
# Global Costmap
# -------------------------------------------------
global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 6.0
    publish_frequency: 3.0
    transform_tolerance: 0.3
    resolution: 0.07
    robot_radius: 0.17
    plugins:
      - "static_layer"
      - "obstacle_layer"
      - "inflation_layer"
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_threshold: 0.5
      track_unknown_space: true
      use_true_map_size: true
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: laser_scan_sensor
      laser_scan_sensor:
        sensor_frame: laser_frame
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.1
        raytrace_max_range: 3.5
        raytrace_min_range: 0.1
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.10
      cost_scaling_factor: 2.0

# -------------------------------------------------
# Local Costmap
# -------------------------------------------------
local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 12.0
    publish_frequency: 6.0
    transform_tolerance: 0.3
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.07
    robot_radius: 0.17
    plugins:
      - "static_layer"
      - "obstacle_layer"
      - "inflation_layer"
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_threshold: 0.0
      enabled: false
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: laser_scan_sensor
      laser_scan_sensor:
        sensor_frame: laser_frame
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        obstacle_max_range: 2.5
        obstacle_min_range: 0.1
        raytrace_max_range: 3.0
        raytrace_min_range: 0.1
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.10
      cost_scaling_factor: 2.0

# -------------------------------------------------
# Recovery Behaviors
# -------------------------------------------------
recoveries_server:
  ros__parameters:
    use_sim_time: false
    plugin_types:
      - "nav2_recoveries::BackUp"
    BackUp:
      plugin: "nav2_recoveries::BackUp"
      backup_distance: 0.3
      velocity: 0.1

# -------------------------------------------------
# Lifecycle Manager
# -------------------------------------------------
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - "slam_toolbox"
      - "planner_server"
      - "controller_server"
      - "recoveries_server"
      - "bt_navigator"
      - "velocity_smoother"

